# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AccountsDummy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccountsDummy
  pod 'Swinject', '2.7.1'
  pod 'SwinjectStoryboard'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

  target 'AccountsDummyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AccountsDummyUITests' do
    # Pods for testing
  end

end
